name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    environment: a
    runs-on: ubuntu-latest
    steps:
      - uses: michcioperz/michci.ooo-action@main
        with:
          token: ${{ secrets.MICHCIOOO_TOKEN }}
